apiVersion: v1
kind: Namespace
metadata:
  name: glasswing-agent
  labels:
    
    helm.sh/chart: glasswing-agent-0.0.0
    app.kubernetes.io/name: glasswing-agent
    app.kubernetes.io/instance: glasswing-agent
    app.kubernetes.io/version: "0.7.0-rc.1"
    app.kubernetes.io/managed-by: Helm
