apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: glasswing-agent
  labels:
    
    helm.sh/chart: glasswing-agent-0.0.0
    app.kubernetes.io/name: glasswing-agent
    app.kubernetes.io/instance: glasswing-agent
    app.kubernetes.io/version: "0.8.0-alpha.8"
    app.kubernetes.io/managed-by: Helm
  namespace: glasswing-agent
  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: glasswing-agent
subjects:
  - kind: ServiceAccount
    name: glasswing-agent
    namespace: glasswing-agent
