apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "glasswing-agent-system:vpa-actor" #glasswing-staging-system:vpa-actor
  
  labels:
    
    helm.sh/chart: glasswing-agent-0.0.0
    app.kubernetes.io/name: glasswing-agent
    app.kubernetes.io/instance: glasswing-agent
    app.kubernetes.io/version: "0.6.3-rc.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "glasswing-agent-system:vpa-actor"
subjects:
    - kind: ServiceAccount
      name: glasswing-agent
      namespace: glasswing-agent
