apiVersion: apps/v1
kind: Deployment
metadata:
  name: glasswing-agent
  namespace: glasswing-agent
  labels:
    
    app: glasswing-agent
    
    helm.sh/chart: glasswing-agent-0.0.0
    app.kubernetes.io/name: glasswing-agent
    app.kubernetes.io/instance: glasswing-agent
    app.kubernetes.io/version: "0.8.0-alpha.6"
    app.kubernetes.io/managed-by: Helm
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glasswing-agent
      app.kubernetes.io/instance: glasswing-agent
  template:
    metadata:
      labels:
        app: glasswing-agent
        app.kubernetes.io/name: glasswing-agent
        app.kubernetes.io/instance: glasswing-agent
    spec:
      shareProcessNamespace: true
      priorityClassName: system-cluster-critical
      serviceAccountName: glasswing-agent
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: agent
          image: "public.ecr.aws/m8h2t8d2/glasswing:0.8.0-alpha.6"
          args:
             - agent
             - --snapshot-interval=15s
             - --v=5
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: API_URL
              value: "https://gateway.glasswing.cloud"
            - name: ENABLE_VPA
              value: "true"
          envFrom:
            - secretRef:
                name: glasswing-agent
          resources: 
              limits:
                cpu: 800m
                memory: 1024Mi
              requests:
                cpu: 500m
                memory: 512Mi
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9876
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /usr/bin/sleep
                - 15s
