apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glasswing-agent:vpa-actor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glasswing-agent:vpa-actor
subjects:
  - kind: ServiceAccount
    name: vpa-updater
    namespace: glasswing-agent
