apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: recommendations.autoscaling.glasswing.cloud
spec:
  group: autoscaling.glasswing.cloud
  names:
    kind: Recommendation
    listKind: RecommendationList
    plural: recommendations
    shortNames:
      - rec
      - vpastat
    singular: recommendation
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          description: Recommendation is the Schema for the recommendations API
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: spec defines the desired state of this Recommendation.
              properties:
                targetRef:
                  description: targetRef identifies the object this recommendation should be applied to.
                  properties:
                    apiVersion:
                      description: apiVersion is the api version of the object.
                      type: string
                    kind:
                      description: kind is the kind of the object.
                      type: string
                    name:
                      description: name is the name of the object.
                      type: string
                  type: object
              required:
                - targetRef
              type: object
            status:
              description: status is the current status of this Recommendation.
              properties:
                message:
                  description: message provides status detail.
                  type: string
                phase:
                  description: phase describes the VPA phase.
                  enum:
                    - New
                    - InProgress
                    - Applied
                    - Failed
                    - Disabled
                  type: string
                recommendationHash:
                  description: RecommendationHash is the hash of the recommendation content in VPA status.
                  type: string
                updateTime:
                  description: updateTime represents the last update time.
                  format: date-time
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
