apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glasswing-agent
  labels:
    
    helm.sh/chart: glasswing-agent-0.0.0
    app.kubernetes.io/name: glasswing-agent
    app.kubernetes.io/instance: glasswing-agent
    app.kubernetes.io/version: "0.7.0-rc.0"
    app.kubernetes.io/managed-by: Helm
  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glasswing-agent
subjects:
  - kind: ServiceAccount
    name: glasswing-agent
    namespace: glasswing-agent
