kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glasswing:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    
    helm.sh/chart: glasswing-agent-0.0.0
    app.kubernetes.io/name: glasswing-agent
    app.kubernetes.io/instance: glasswing-agent
    app.kubernetes.io/version: "0.7.0-rc.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - autoscaling.glasswing.cloud
  resources:
  - verticalscalingconfigurations
  verbs:
  - get
  - list
  - watch
