apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: glasswing-agent:leader-locking-vpa-recommender
  namespace: glasswing-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: glasswing-agent:leader-locking-vpa-recommender
subjects:
  - kind: ServiceAccount
    name: vpa-recommender
    namespace: glasswing-agent
